import { sqliteTable, text, integer, real, index, uniqueIndex } from 'drizzle-orm/sqlite-core';
export const leads = sqliteTable('leads',{services:text('services').notNull().default(''),billing:text('billing').notNull().default('Estimado'),closedAt:text('closed_at').notNull().default(''),id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),campaignId:text('campaign_id').references(()=>campaigns.id,{onDelete:'set null'}),name:text('name').notNull(),email:text('email').notNull().default(''),industry:text('industry').notNull().default(''),contact:text('contact').notNull().default(''),source:text('source').notNull().default('Otro'),stage:text('stage').notNull().default('Nuevos'),value:real('value').notNull().default(0),followUp:text('follow_up').notNull().default(''),notes:text('notes').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('leads_company_stage').on(t.companyId,t.stage)]);
export const leadEvents = sqliteTable('lead_events',{id:text('id').primaryKey(),leadId:text('lead_id').notNull().references(()=>leads.id,{onDelete:'cascade'}),type:text('type').notNull(),detail:text('detail').notNull(),actor:text('actor').notNull(),occurredAt:text('occurred_at').notNull(),createdAt:text('created_at').notNull()},t=>[index('lead_events_lead_date').on(t.leadId,t.occurredAt)]);
export const companies = sqliteTable('companies',{industry:text('industry').notNull().default(''),logoKey:text('logo_key').notNull().default(''),theme:text('theme').notNull().default('getpes'),showMeetings:integer('show_meetings').notNull().default(1),id:text('id').primaryKey(),name:text('name').notNull(),createdAt:text('created_at').notNull()});
export const users = sqliteTable('users',{hideBranding:integer('hide_branding').notNull().default(0),displayName:text('display_name').notNull().default(''),phone:text('phone').notNull().default(''),permissions:text('permissions').notNull().default('[]'),theme:text('theme'),id:text('id').primaryKey(),username:text('username').notNull().unique(),passwordHash:text('password_hash').notNull(),role:text('role').notNull(),companyId:text('company_id').references(()=>companies.id),active:integer('active').notNull().default(1),mustChange:integer('must_change').notNull().default(1)});
export const sessions = sqliteTable('sessions',{token:text('token').primaryKey(),userId:text('user_id').notNull().references(()=>users.id),expires:integer('expires').notNull()});
export const loginAttempts = sqliteTable('login_attempts',{key:text('key').primaryKey(),count:integer('count').notNull(),resetAt:integer('reset_at').notNull()});
export const campaigns = sqliteTable('campaigns',{meetings:integer('meetings'),status:text('status').notNull().default('Sin definir'),startDate:text('start_date').notNull().default(''),endDate:text('end_date').notNull().default(''),id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),month:text('month').notNull(),name:text('name').notNull(),platform:text('platform').notNull(),objective:text('objective').notNull(),audience:text('audience').notNull().default(''),days:integer('days').notNull().default(0),dailyBudget:real('daily_budget').notNull().default(0),frequency:real('frequency').notNull().default(0),spend:real('spend').notNull().default(0),impressions:integer('impressions').notNull().default(0),clicks:integer('clicks').notNull().default(0),leads:integer('leads').notNull().default(0),sales:integer('sales').notNull().default(0),revenue:real('revenue').notNull().default(0),notes:text('notes').notNull().default('')},t=>[index('campaigns_company_month').on(t.companyId,t.month)]);
export const tasks = sqliteTable('tasks',{subtype:text('subtype').notNull().default(''),endTime:text('end_time').notNull().default(''),time:text('time').notNull().default(''),approval:text('approval').notNull().default('Pendiente'),approvedBy:text('approved_by').notNull().default(''),id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),date:text('date').notNull(),title:text('title').notNull(),type:text('type').notNull(),status:text('status').notNull(),notes:text('notes').notNull().default(''),url:text('url').notNull().default('')},t=>[index('tasks_company_date').on(t.companyId,t.date)]);
export const reports = sqliteTable('reports',{id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),month:text('month').notNull(),title:text('title').notNull(),summary:text('summary').notNull(),nextSteps:text('next_steps').notNull(),config:text('config').notNull(),published:integer('published').notNull().default(0),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('reports_company_month').on(t.companyId,t.month)]);

export const campaignMetrics = sqliteTable('campaign_metrics',{id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),month:text('month').notNull(),leads:integer('leads'),revenue:real('revenue'),meetings:integer('meetings'),sales:integer('sales')},t=>[uniqueIndex('campaign_metrics_company_month').on(t.companyId,t.month)]);

export const userCompanies=sqliteTable('user_companies',{id:text('id').primaryKey(),userId:text('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}),companyId:text('company_id').notNull().references(()=>companies.id)},t=>[uniqueIndex('user_companies_unique').on(t.userId,t.companyId)]);
export const accessRequests=sqliteTable('access_requests',{id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id),requester:text('requester').notNull().references(()=>users.id),type:text('type').notNull(),detail:text('detail').notNull(),status:text('status').notNull().default('Pendiente'),createdAt:text('created_at').notNull()});

export const dashboardPreferences=sqliteTable('dashboard_preferences',{companyId:text('company_id').primaryKey().references(()=>companies.id),settings:text('settings').notNull().default('{}')});

export const socialConnections=sqliteTable('social_connections',{id:text('id').primaryKey(),companyId:text('company_id').notNull().references(()=>companies.id,{onDelete:'cascade'}),platform:text('platform').notNull(),status:text('status').notNull().default('pending'),accountName:text('account_name').notNull().default(''),externalId:text('external_id'),lastSynced:text('last_synced'),createdAt:text('created_at').notNull()},t=>[uniqueIndex('social_company_platform').on(t.companyId,t.platform)]);
export const socialDaily=sqliteTable('social_daily',{id:text('id').primaryKey(),connectionId:text('connection_id').notNull().references(()=>socialConnections.id,{onDelete:'cascade'}),date:text('date').notNull(),followers:integer('followers'),views:integer('views'),reach:integer('reach')},t=>[uniqueIndex('social_daily_account_date').on(t.connectionId,t.date)]);
export const socialPosts=sqliteTable('social_posts',{id:text('id').primaryKey(),connectionId:text('connection_id').notNull().references(()=>socialConnections.id,{onDelete:'cascade'}),externalId:text('external_id').notNull(),publishedAt:text('published_at').notNull(),title:text('title').notNull().default(''),url:text('url').notNull().default(''),kind:text('kind').notNull().default('Post'),views:integer('views'),reach:integer('reach'),likes:integer('likes')},t=>[uniqueIndex('social_posts_external').on(t.connectionId,t.externalId)]);
