import test from 'node:test';import assert from 'node:assert/strict';import {api,hashPassword} from '../src/api.mjs';import {database} from './local-db.mjs';
test('website intake saves once with automatic history and never accepts a target company',async()=>{
 const DB=database(),env={DB};
 const body={request_id:crypto.randomUUID(),name:'Consulta de prueba',email:'test@example.com',contact:'+51 999 999 999',industry:'Gastronomía',service:'video',message:'Necesito un video',company_id:'lgna',stage:'Ganados'};
 const call=async(data=body,origin='https://test.local')=>api(new Request('https://test.local/api/contact',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(data)}),env);
 assert.equal((await call({...body,email:'invalid'})).status,400);
 assert.equal((await call(body,'https://other.local')).status,403);
 assert.equal((await call({...body,website:'spam'})).status,400);
 assert.equal((await call()).status,200);
 assert.equal((await call()).status,200);
 const rows=(await DB.prepare('SELECT * FROM leads').all()).results;
 assert.equal(rows.length,1);assert.equal(rows[0].company_id,'getpes');assert.equal(rows[0].stage,'Nuevos');assert.equal(rows[0].email,body.email);assert.equal(rows[0].industry,body.industry);assert.match(rows[0].notes,/Necesito un video/);
 const events=(await DB.prepare('SELECT * FROM lead_events').all()).results;
 assert.equal(events.length,1);assert.equal(events[0].actor,'Formulario web');
 assert.equal((await api(new Request('https://test.local/api/data?company=getpes&month=2026-09'),env)).status,401);
 for(let i=0;i<8;i++)assert.equal((await call()).status,200);
 assert.equal((await call()).status,429);
});
test('authentication, company isolation, report visibility and CRUD',async()=>{
 const DB=database(),env={DB,BOOTSTRAP_ADMIN_HASH:await hashPassword('Temporary-admin-12345'),BOOTSTRAP_LGNA_HASH:await hashPassword('Temporary-client-12345')};
 async function call(path,body,cookie='',method){const r=await api(new Request('https://test.local'+path,{method:method||(body?'POST':'GET'),headers:{origin:'https://test.local','content-type':'application/json',cookie},body:body?JSON.stringify(body):undefined}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]||''};}
 assert.equal((await call('/api/data?company=lgna&month=2026-09')).status,401);
 let a=await call('/api/login',{username:'admin@getpes.com',password:'Temporary-admin-12345'});assert.equal(a.status,200);let ac=a.cookie;
 assert.equal((await call('/api/companies',null,ac)).status,403);
 assert.equal((await call('/api/password',{current:'Temporary-admin-12345',password:'New-admin-pass-56789'},ac)).status,200);
 assert.equal((await call('/api/companies',null,ac)).status,401);
 ac=(await call('/api/login',{username:'admin@getpes.com',password:'New-admin-pass-56789'})).cookie;
 let c=await call('/api/login',{username:'lgna@getpes.com',password:'Temporary-client-12345'});await call('/api/password',{current:'Temporary-client-12345',password:'New-client-pass-56789'},c.cookie);const cc=(await call('/api/login',{username:'lgna@getpes.com',password:'New-client-pass-56789'})).cookie;
 await call('/api/companies',{name:'Other company'},ac);const companies=(await call('/api/companies',null,ac)).data.companies,other=companies.find(c=>c.id!=='lgna').id;
 assert.equal((await call('/api/data?company='+other+'&month=2026-09',null,cc)).status,403);
 assert.equal((await call('/api/companies',null,cc)).data.companies.length,1);
 const campaign={company_id:'lgna',month:'2026-09',name:'Test campaign',platform:'Meta Ads',objective:'Leads',spend:100,impressions:1000,clicks:100,leads:10,sales:2,revenue:500};
 assert.equal((await call('/api/campaigns',campaign,cc)).status,403);assert.equal((await call('/api/campaigns',campaign,ac)).status,200);
 assert.equal((await call('/api/campaigns',{...campaign,spend:-2},ac)).status,400);
 const campaignId=(await call('/api/data?company=lgna&month=2026-09',null,ac)).data.campaigns[0].id;
 assert.equal((await call('/api/campaigns',{...campaign,id:campaignId,meetings:3.5},ac)).status,400);
 assert.equal((await call('/api/campaigns',{...campaign,id:campaignId,meetings:4},ac)).status,200);
 assert.equal((await call('/api/campaigns',{...campaign,id:campaignId},ac)).status,200);
 const meetingData=(await call('/api/data?company=lgna&month=2026-09',null,cc)).data;
 assert.equal(meetingData.campaigns[0].meetings,4);
 assert.equal(meetingData.summary.meetings,4);
 assert.equal(meetingData.trend.find(r=>r.month==='2026-09').meetings,4);

 const metric={company_id:'lgna',month:'2026-09',key:'meetings',value:12};
 assert.equal((await call('/api/appearance',{scope:'company',company_id:'lgna',theme:'blue'},cc)).status,403);
 assert.equal((await call('/api/appearance',{scope:'company',company_id:'lgna',theme:'blue'},ac)).status,200);
 assert.equal((await call('/api/appearance',{scope:'personal',theme:'red'},cc)).status,200);
 assert.equal((await call('/api/session',null,cc)).data.user.theme,'red');
 assert.equal((await call('/api/session',null,ac)).data.user.theme,null);
 assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.companySettings.theme,'blue');
 assert.equal((await call('/api/data?company='+other+'&month=2026-09',null,ac)).data.companySettings.theme,'getpes');
 assert.equal((await call('/api/appearance',{scope:'personal',theme:'invalid'},cc)).status,400);
 assert.equal((await call('/api/appearance',{scope:'personal',theme:null},cc)).status,200);
 assert.equal((await call('/api/session',null,cc)).data.user.theme,null);
 assert.equal((await call('/api/company-settings',{company_id:'lgna',show_meetings:false},cc)).status,403);
 assert.equal((await call('/api/company-settings',{company_id:'lgna',show_meetings:false},ac)).status,200);
 assert.equal((await call('/api/data?company=lgna&month=2026-10',null,cc)).data.companySettings.show_meetings,0);
 assert.equal((await call('/api/data?company='+other+'&month=2026-09',null,ac)).data.companySettings.show_meetings,1);
 assert.equal((await call('/api/campaign-metrics',metric,cc)).status,403);
 assert.equal((await call('/api/campaign-metrics',{...metric,value:-1},ac)).status,400);
 assert.equal((await call('/api/campaign-metrics',metric,ac)).status,200);
 assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.campaignMetrics.meetings,12);
 assert.equal((await call('/api/data?company=lgna&month=2026-10',null,cc)).data.campaignMetrics,null);
 assert.equal((await call('/api/data?company='+other+'&month=2026-09',null,ac)).data.campaignMetrics,null);
 assert.equal((await call('/api/campaign-metrics',{...metric,value:null},ac)).status,200);
 assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.campaignMetrics.meetings,null);
 await call('/api/campaigns',{...campaign,platform:'Google Ads',spend:50,leads:5},ac);
 await call('/api/campaigns',{...campaign,month:'2027-12',spend:80,leads:0},ac);
 await call('/api/campaigns',{...campaign,company_id:other,spend:999},ac);
 const comparison=(await call('/api/data?company=lgna&month=2026-09',null,cc)).data.comparison;
 assert.deepEqual(comparison,[{month:'2026-09',entries:2,spend:150,leads:15,revenue:1000},{month:'2027-12',entries:1,spend:80,leads:0,revenue:500}]);
 const task={company_id:'lgna',title:'Grabación',date:'2026-09-15',type:'Grabación',status:'Pendiente',notes:'Details',url:''};
 const prospect={company_id:'lgna',name:'Prospecto de prueba',contact:'test@example.com',stage:'Nuevos',source:'Referido',value:250,follow_up:'2027-01-05',notes:'Test'};
 assert.equal((await call('/api/leads',prospect,cc)).status,403);
 assert.equal((await call('/api/leads',prospect,ac)).status,200);
 const emailProspect={...prospect,email:'ventas@example.com',industry:'Inmobiliaria'};
 assert.equal((await call('/api/leads',{...emailProspect,email:'correo-invalido'},ac)).status,400);
 let prospects=(await call('/api/data?company=lgna&month=2026-09',null,cc)).data.leads;assert.equal(prospects.length,1);const prospectId=prospects[0].id;
 assert.equal((await call('/api/leads',{...emailProspect,id:prospectId,services:'Gestión de redes, Video',billing:'Mensual'},ac)).status,200);
 const savedProspect=(await call('/api/data?company=lgna&month=2026-09',null,cc)).data.leads[0];
 assert.equal(savedProspect.email,'ventas@example.com');assert.equal(savedProspect.industry,'Inmobiliaria');
 assert.equal((await call('/api/leads',{...prospect,id:prospectId,company_id:other},ac)).status,404);
 assert.equal((await call('/api/leads',{...prospect,id:prospectId,stage:'Invalid'},ac,'PATCH')).status,400);
 assert.equal((await call('/api/leads',{...prospect,id:prospectId,stage:'Ganados'},cc,'PATCH')).status,403);
 assert.equal((await call('/api/leads',{...prospect,id:prospectId,stage:'Ganados'},ac,'PATCH')).status,200);
 const won=await env.DB.prepare('SELECT * FROM leads WHERE id=?').bind(prospectId).first();assert.equal(won.billing,'Mensual');assert.equal(won.services,'Gestión de redes, Video');assert.match(won.closed_at,/^\d{4}-\d{2}-\d{2}$/);
 assert.equal((await call('/api/data?company=lgna&month=2027-12',null,cc)).data.leads[0].stage,'Ganados');
 assert.equal((await call('/api/data?company='+other+'&month=2026-09',null,ac)).data.leads.length,0);
 const eventPath='/api/lead-events?company=lgna&lead='+prospectId;
 let history=(await call(eventPath,null,cc)).data.events;assert.equal(history.length,2);assert.ok(history.some(e=>e.type==='Cambio de etapa'&&e.detail==='Nuevos → Ganados'));
 await call('/api/leads',{...prospect,id:prospectId,stage:'Ganados'},ac,'PATCH');assert.equal((await call(eventPath,null,cc)).data.events.length,2);
 const activity={company_id:'lgna',lead_id:prospectId,type:'Llamada registrada',detail:'Solicita propuesta',occurred_at:'2026-09-01T15:00:00.000Z'};
 assert.equal((await call('/api/lead-events',activity,cc)).status,403);
 assert.equal((await call('/api/lead-events',{...activity,type:'Cambio de etapa'},ac)).status,400);
 assert.equal((await call('/api/lead-events',{...activity,occurred_at:'2099-01-01T00:00:00Z'},ac)).status,400);
 assert.equal((await call('/api/lead-events',{...activity,company_id:other},ac)).status,404);
 assert.equal((await call('/api/lead-events',{...activity,actor:'forged'},ac)).status,200);
 history=(await call(eventPath,null,cc)).data.events;assert.equal(history.length,3);assert.equal(history.find(e=>e.type==='Llamada registrada').actor,'admin@getpes.com');
 const available=(await call('/api/data?company=lgna&month=2026-09',null,ac)).data.pipelineCampaigns;
 const foreignCampaign=(await call('/api/data?company='+other+'&month=2026-09',null,ac)).data.pipelineCampaigns[0].id;
 assert.equal((await call('/api/leads',{...prospect,id:prospectId,campaign_id:foreignCampaign},ac)).status,400);
 assert.equal((await call('/api/leads',{...prospect,id:prospectId,campaign_id:available[0].id},ac)).status,200);
 assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.leads[0].campaign_id,available[0].id);
 assert.equal((await call('/api/leads',{...prospect,id:prospectId},ac,'DELETE')).status,200);
 assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.leads.length,0);
 assert.equal((await call(eventPath,null,cc)).status,404);
 assert.equal((await call('/api/tasks',task,ac)).status,200);assert.equal((await call('/api/tasks',{...task,url:'javascript:alert(1)'},ac)).status,400);
 let data=(await call('/api/data?company=lgna&month=2026-09',null,cc)).data;assert.equal(data.campaigns.length,2);assert.equal(data.tasks.length,1);
 assert.equal((await call('/api/tasks',{...task,id:data.tasks[0].id,company_id:other},ac)).status,404);
 const report={company_id:'lgna',month:'2026-09',title:'Monthly report',summary:'Results',next_steps:'Next',config:{campaigns:true,calendar:true,deliverables:false},published:false};
 assert.equal((await call('/api/reports',report,ac)).status,200);assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.report,null);
 await call('/api/reports',{...report,published:true},ac);assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).data.report.title,'Monthly report');
 assert.equal((await call('/api/data?company=lgna&month=2026-10',null,cc)).data.campaigns.length,0);
 const forged=await api(new Request('https://test.local/api/tasks',{method:'POST',headers:{origin:'https://evil.local','content-type':'application/json',cookie:ac},body:JSON.stringify(task)}),env);assert.equal(forged.status,403);
 const created=await call('/api/users',{username:'reader@getpes.com',company_id:other},ac);assert.ok(created.data.password);assert.equal((await call('/api/users',null,cc)).status,403);
 const reader=(await call('/api/users',null,ac)).data.users.find(x=>x.username==='reader@getpes.com');await call('/api/users',{action:'disable',id:reader.id},ac);assert.equal((await call('/api/login',{username:'reader@getpes.com',password:created.data.password})).status,401);
 await call('/api/logout',{},cc);assert.equal((await call('/api/data?company=lgna&month=2026-09',null,cc)).status,401);
 for(let i=0;i<11;i++)c=await call('/api/login',{username:'missing@getpes.com',password:'Wrong-password'});assert.equal(c.status,429);DB.close();
});
