import test from 'node:test';import assert from 'node:assert/strict';import {api,hashPassword} from '../src/api.mjs';import {database} from './local-db.mjs';
test('campaign dates stay linked and batch tasks enforce atomic company boundaries',async()=>{
 const DB=database(),env={DB},password='Calendar-test-only-2026',hash=await hashPassword(password);
 for(const id of ['a','b','getpes'])await DB.prepare('INSERT INTO companies(id,name,created_at) VALUES(?,?,?)').bind(id,id,'2026-09-27').run();
 for(const [id,role] of [['admin','admin'],['owner','company_admin']])await DB.prepare('INSERT INTO users(id,username,password_hash,role,company_id,must_change) VALUES(?,?,?,?,?,0)').bind(id,id+'@test.local',hash,role,'a').run();
 const call=async(path,body,cookie='',method)=>{const r=await api(new Request('https://test.local'+path,{method:method||(body?'POST':'GET'),headers:{origin:'https://test.local','content-type':'application/json',cookie},body:body?JSON.stringify(body):undefined}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const admin=(await call('/api/login',{username:'admin@test.local',password})).cookie,owner=(await call('/api/login',{username:'owner@test.local',password})).cookie;
 const parts=new Intl.DateTimeFormat('en-US',{timeZone:'America/Lima',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date()),part=k=>parts.find(p=>p.type===k).value,today=part('year')+'-'+part('month')+'-'+part('day');
 for(const [id,cid,status,when] of [['up-a','a','Pendiente',today],['up-b','b','Pendiente',today],['done','a','Completado',today],['old','a','Pendiente','2020-01-01']])await DB.prepare('INSERT INTO tasks(id,company_id,title,type,status,date) VALUES(?,?,?,?,?,?)').bind(id,cid,id,'Reunión',status,when).run();
 await DB.prepare("INSERT INTO tasks(id,company_id,title,type,status,date) VALUES('not-alert','a','Design','Diseño','Pendiente',?)").bind(today).run();
 assert.equal((await call('/api/upcoming',null,owner)).data.total,1);
 assert.equal((await call('/api/upcoming',null,admin)).data.total,2);
 assert.equal((await call('/api/upcoming',null,owner)).data.events[0].id,'up-a');
 await DB.prepare("DELETE FROM tasks WHERE id IN ('up-a','up-b','done','old','not-alert')").run();
 const campaign={company_id:'a',month:'2026-09',start_date:'2026-09-30',end_date:'2026-10-05',name:'Linked',platform:'Meta Ads',objective:'Leads',spend:0,impressions:0,clicks:0,leads:0,sales:0,revenue:0};
 assert.equal((await call('/api/campaigns',campaign,admin)).status,200);
 const read=async(company,month,cookie=admin)=>(await call('/api/data?company='+company+'&month='+month,null,cookie)).data;
 const c=(await read('a','2026-10')).calendarCampaigns[0];assert.equal(c.end_date,'2026-10-05');assert.equal((await read('b','2026-10')).calendarCampaigns.length,0);assert.equal((await read('getpes','2026-10')).calendarCampaigns.length,1);
 await call('/api/campaigns',{...campaign,id:c.id,end_date:'2026-11-05'},admin);assert.equal((await read('a','2026-10')).calendarCampaigns.length,0);assert.equal((await read('a','2026-11')).calendarCampaigns.length,1);
 for(const company_id of ['a','a','b'])await call('/api/tasks',{company_id,title:'Task',date:'2026-09-27',type:'Grabación',time:'12:00',end_time:'16:00'},admin);
 const tasks=(await read('a','2026-09')).tasks,foreign=(await read('b','2026-09')).tasks[0];
 const items=tasks.map(t=>({id:t.id,company_id:t.company_id,date:'2026-10-02'}));
 assert.equal((await call('/api/tasks/batch',{action:'move',items:[items[0],{id:foreign.id,company_id:'b',date:'2026-10-02'}]},owner)).status,403);
 assert.equal((await read('a','2026-09')).tasks.length,2);
 assert.equal((await call('/api/tasks/batch',{action:'copy',items},owner)).status,200);
 const copies=(await read('a','2026-10')).tasks;assert.equal(copies.length,2);assert.equal(copies[0].time,'12:00');assert.equal(copies[0].end_time,'16:00');assert.equal(copies[0].status,'Pendiente');
 assert.equal((await call('/api/tasks/batch',{action:'move',items},owner)).status,200);assert.equal((await read('a','2026-09')).tasks.length,0);assert.equal((await read('a','2026-10')).tasks.length,4);
 const copied=(await call('/api/tasks/batch',{action:'copy',items:[items[0]]},owner)).data;
 const snapshot=copied.records[0];assert.ok(snapshot.id);assert.notEqual(snapshot.id,items[0].id);
 const deletion={action:'delete',items:[{id:snapshot.id,company_id:'a',date:snapshot.date,expected:snapshot}]};
 assert.equal((await call('/api/tasks/batch',deletion,owner)).status,200);
 assert.equal((await DB.prepare('SELECT id FROM tasks WHERE id=?').bind(items[0].id).first()).id,items[0].id);
 assert.equal((await call('/api/tasks/batch',{action:'move',items:[{...items[0],date:'2026-10-03',expected_date:'2020-01-01'}]},owner)).status,409);
 await call('/api/campaigns',{id:c.id,company_id:'a'},admin,'DELETE');assert.equal((await read('a','2026-11')).calendarCampaigns.length,0);DB.close();
});
import vm from 'node:vm';import {readFileSync} from 'node:fs';
test('calendar projects campaign milestones and preserves relative dates for grouped moves',()=>{
 const context=vm.createContext({state:{view:'calendario',company:'a',month:'2026-09',companies:[{id:'a',name:'A'}],data:{tasks:[{id:'t',company_id:'a',title:'Shoot',date:'2026-09-30',type:'Grabación'}],calendarCampaigns:[{id:'c',company_id:'a',name:'Launch',platform:'Meta Ads',start_date:'2026-09-30',end_date:'2026-10-02'}]}},document:{addEventListener(){}},canEditTask:()=>true,esc:v=>String(v??''),fullDate:x=>x});
 vm.runInContext(readFileSync('public/js/calendar-next.js','utf8'),context);
 assert.equal(vm.runInContext('calendarTasks().length',context),2);
 assert.equal(vm.runInContext("shiftedDate('2026-09-30',3)",context),'2026-10-03');
 const marker=vm.runInContext('activityCard(calendarTasks()[1],true)',context);assert.match(marker,/Inicio/);assert.match(marker,/draggable="false"/);assert.doesNotMatch(marker,/data-select-activity|data-delete-task/);
 vm.runInContext("calendarSelectionMode=true;calendarSelection.add('t')",context);
 assert.match(vm.runInContext('activityCard(calendarTasks()[0],true)',context),/selected-activity/);
 assert.equal(vm.runInContext('selectedActivities().length',context),1);
});
