import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';import {api,hashPassword} from '../src/api.mjs';import {database} from './local-db.mjs';
const ctx=vm.createContext({});vm.runInContext(fs.readFileSync('public/vendor/xlsx.full.min.js','utf8'),ctx);vm.runInContext(fs.readFileSync('public/js/meta-import.js','utf8')+';this.parser=MetaImport;',ctx);const {parser,XLSX}=ctx;
const options={month:'2026-09',currency:'PEN'};
test('CSV and XLSX normalize actual Meta headers, quoted names, localized amounts and dates',()=>{
 const csv='Nombre de la campaña;Importe gastado (PEN);Impresiones;Clics en el enlace;Resultados;Indicador de resultado;Inicio del informe;Fin del informe\r\n"Campaña; prueba";"1.234,50";"12.345";45;12;actions:lead;01/09/2026;30/09/2026\r\n';
 const book=XLSX.read(csv,{type:'string',raw:true}),matrix=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1,raw:true});const result=parser.normalize(matrix,options);assert.equal(result.errors.length,0);assert.equal(result.rows[0].spend,1234.5);assert.equal(result.rows[0].impressions,12345);assert.equal(result.rows[0].leads,12);assert.equal(result.rows[0].name,'Campaña; prueba');assert.equal(result.rows[0].start_date,'');assert.equal(parser.number('1.234',false,true),1.234);
 const xbook=XLSX.utils.book_new();XLSX.utils.book_append_sheet(xbook,XLSX.utils.aoa_to_sheet([['Campaign name','Amount spent (USD)','Purchases','Purchases conversion value','Starts'],['Sales',125.50,3,600,46266]]),'Data');const bytes=XLSX.write(xbook,{type:'array',bookType:'xlsx'}),read=XLSX.read(bytes,{type:'array'});const x=parser.normalize(XLSX.utils.sheet_to_json(read.Sheets.Data,{header:1,raw:true}),{...options,currency:'USD'});assert.equal(x.errors.length,0);assert.equal(x.rows[0].revenue,600);assert.equal(x.rows[0].sales,3);assert.match(x.rows[0].start_date,/^2026-/);
});
test('invalid dates, currencies, duplicate breakdowns and ambiguous results do not silently import',()=>{
 assert.equal(parser.normalize([['Campaign name','Amount spent (USD)'],['A',10]],options).errors.length,1);
 assert.equal(parser.normalize([['Campaign name','Amount spent','Starts'],['A',10,'31/02/2026']],options).errors.length,1);
 assert.equal(parser.normalize([['Campaign name','Amount spent'],['A',10],['A',20]],options).errors.length,1);
 const result=parser.normalize([['Campaign name','Amount spent','Results'],['A',10,20]],options);assert.equal(result.rows[0].leads,0);assert.equal(result.warnings.length,1);
 assert.equal(parser.normalize([['Campaign name','Amount spent','Reporting starts','Reporting ends'],['A',10,'2026-08-01','2026-09-30']],options).errors.length,1);
});
test('bulk import is company-scoped, validated before saving, and safe to retry',async()=>{
 const DB=database(),hash=await hashPassword('test-pass');for(const id of ['a','b'])await DB.prepare('INSERT INTO companies(id,name,created_at) VALUES(?,?,?)').bind(id,id,'2026-09-01').run();await DB.prepare('INSERT INTO users(id,username,password_hash,role,company_id,must_change) VALUES(?,?,?,?,?,0)').bind('u','import@test.local',hash,'company_admin','a').run();let cookie='';const call=async(path,body)=>{const r=await api(new Request('https://test.local'+path,{method:'POST',headers:{origin:'https://test.local','content-type':'application/json',cookie},body:JSON.stringify(body)}),{DB});if(path==='/api/login')cookie=r.headers.get('set-cookie').split(';')[0];return {status:r.status,data:await r.json()};};await call('/api/login',{username:'import@test.local',password:'test-pass'});
 const row=parser.normalize([['Campaign name','Amount spent'],['A',100]],options).rows[0],payload={company_id:'a',currency:'PEN',rows:[row]};assert.equal((await call('/api/campaigns/import',{...payload,company_id:'b'})).status,403);assert.equal((await call('/api/campaigns/import',{...payload,rows:[row,{...row,name:'Bad',spend:-10}]})).status,400);assert.equal((await DB.prepare('SELECT COUNT(*) AS n FROM campaigns').first()).n,0);
 assert.equal((await call('/api/campaigns/import',payload)).data.created,1);assert.equal((await call('/api/campaigns/import',payload)).data.skipped,1);const saved=await DB.prepare('SELECT * FROM campaigns').first();assert.equal(saved.spend,100);assert.equal(saved.meetings,null);assert.equal(saved.platform,'Meta Ads');const repair=await call('/api/campaigns/import',{...payload,rows:[{...row,leads:7,leads_from_messages:true}]});assert.equal(repair.data.updated,1);assert.equal((await DB.prepare('SELECT * FROM campaigns').first()).leads,7);assert.equal((await call('/api/campaigns/import',{...payload,rows:[{...row,leads:9,leads_from_messages:true}]})).data.updated,0);assert.equal((await call('/api/campaigns/import',{...payload,currency:'USD'})).status,400);
});

test('Spanish messaging export preserves result type, daily ad-set budget and reporting period',()=>{const result=parser.normalize([['Inicio del informe','Fin del informe','Nombre de la campaña','Entrega de la campaña','Resultados','Indicador de resultado','Costo por resultados','Presupuesto del conjunto de anuncios','Tipo de presupuesto del conjunto de anuncios','Importe gastado (USD)','Impresiones','Alcance','Finalización','Configuración de atribución'],['2026-09-25','2026-09-28','Campaña de prueba','active',7,'actions:onsite_conversion.messaging_conversation_started_7d',4.16714286,8.5,'Diario',29.17,2762,1996,'En curso','7 días tras clic o 1 día tras visualización']],{month:'2026-09',currency:'USD'});assert.equal(result.errors.length,0);const row=result.rows[0];assert.equal(row.import_result_label,'Conversaciones iniciadas por mensaje');assert.equal(row.import_result,7);assert.equal(row.daily_budget,8.5);assert.equal(row.spend,29.17);assert.equal(row.leads,7);assert.equal(row.leads_from_messages,true);assert.equal(row.end_date,'');assert.equal(row.start_date,'');assert.match(row.notes,/Alcance: 1996/);assert.match(row.notes,/2026-09-25 a 2026-09-28/);assert.match(row.notes,/4.16714286 USD/);});
