import test from 'node:test';import assert from 'node:assert/strict';import {api,hashPassword} from '../src/api.mjs';import {database} from './local-db.mjs';
test('three roles enforce company boundaries, write permissions, approvals and access requests',async()=>{
 const DB=database(),env={DB},password='Test-only-password-2026',hash=await hashPassword(password);
 for(const id of ['a','b'])await DB.prepare('INSERT INTO companies(id,name,created_at) VALUES(?,?,?)').bind(id,id,new Date().toISOString()).run();
 for(const [id,role,cid,permissions] of [['root','admin',null,[]],['worker','staff',null,['calendar.view','calendar.manage']],['owner','company_admin','a',[]]])await DB.prepare('INSERT INTO users(id,username,password_hash,role,company_id,must_change,permissions) VALUES(?,?,?,?,?,0,?)').bind(id,id+'@getpes.com',hash,role,cid,JSON.stringify(permissions)).run();
 await DB.prepare('INSERT INTO user_companies(id,user_id,company_id) VALUES(?,?,?)').bind('assigned','worker','a').run();
 const call=async(path,body,cookie='',method)=>{const r=await api(new Request('https://test.local'+path,{method:method||(body?'POST':'GET'),headers:{origin:'https://test.local','content-type':'application/json',cookie},body:body?JSON.stringify(body):undefined}),env);return {status:r.status,data:await r.json(),cookie:r.headers.get('set-cookie')?.split(';')[0]};};
 const login=async id=>(await call('/api/login',{username:id+'@getpes.com',password})).cookie;
 const root=await login('root'),worker=await login('worker'),owner=await login('owner');
 for(const cookie of [worker,owner]){assert.equal((await call('/api/data?company=b&month=2026-09',null,cookie)).status,403);assert.equal((await call('/api/users',null,cookie)).status,403);assert.equal((await call('/api/companies',{name:'Forged'},cookie)).status,403);assert.equal((await call('/api/companies',null,cookie)).data.companies.length,1);}
 const currencyPreferences={objective:'leads',indicators:['spend','leads','cpl','sales','roas'],columns:['name','spend'],currency:'USD'};
 assert.equal((await call('/api/dashboard-preferences',{company_id:'a',preferences:currencyPreferences},worker)).status,403);
 assert.equal((await call('/api/dashboard-preferences',{company_id:'a',preferences:currencyPreferences},owner)).status,200);
 assert.equal((await call('/api/data?company=a&month=2026-09',null,owner)).data.dashboardPreferences.currency,'USD');
 assert.equal((await call('/api/data?company=b&month=2026-09',null,root)).data.dashboardPreferences,null);
 assert.equal((await call('/api/dashboard-preferences',{company_id:'a',preferences:{...currencyPreferences,currency:'BAD'}},owner)).status,400);
 const {currency,...withoutCurrency}=currencyPreferences;
 await call('/api/dashboard-preferences',{company_id:'a',preferences:withoutCurrency},owner);
 assert.equal((await call('/api/data?company=a&month=2026-09',null,owner)).data.dashboardPreferences.currency,'USD');
 const images=new Map();env.BUCKET={put:async(k,v)=>images.set(k,v),get:async k=>images.has(k)?{body:images.get(k)}:null};
 const logo='data:image/jpeg;base64,'+Buffer.from([255,216,255,224,255,217]).toString('base64');
 assert.equal((await call('/api/companies',{id:'b',name:'b',industry:'Servicios',logo},worker,'PATCH')).status,403);
 assert.equal((await call('/api/companies',{id:'b',name:'b',industry:'Servicios',logo},root,'PATCH')).status,200);
 assert.equal((await call('/api/companies',null,root)).data.companies.find(c=>c.id==='b').industry,'Servicios');
 const imageRead=async cookie=>api(new Request('https://test.local/api/company-logo?company=b',{headers:{cookie}}),env);
 assert.equal((await imageRead(worker)).status,403);assert.equal((await imageRead(root)).headers.get('content-type'),'image/jpeg');
 assert.equal(images.size,1);
 for(const theme of ['neon','white','getpes']){
 assert.equal((await call('/api/appearance',{scope:'personal',theme},root)).status,200);
 assert.equal((await call('/api/session',null,root)).data.user.theme,theme);
 }
 assert.equal((await call('/api/appearance',{scope:'personal',theme:'getpes',hide_branding:true},root)).status,403);
 await DB.prepare('INSERT INTO users(id,username,password_hash,role,company_id,must_change) VALUES(?,?,?,?,?,0)').bind('group','grupoe@getpes.com',hash,'company_admin','a').run();
 const group=(await call('/api/login',{username:'grupoe@getpes.com',password})).cookie;
 assert.equal((await call('/api/appearance',{scope:'personal',theme:'white',hide_branding:true},group)).status,200);
 assert.equal((await call('/api/session',null,group)).data.user.hide_branding,1);
 assert.equal((await call('/api/appearance',{scope:'personal',theme:'getpes',hide_branding:false},group)).status,200);
 assert.equal((await call('/api/session',null,group)).data.user.hide_branding,0);
 await DB.prepare("DELETE FROM sessions WHERE user_id='group'").run();await DB.prepare("DELETE FROM users WHERE id='group'").run();
 const campaign={company_id:'a',month:'2026-09',name:'Private campaign',platform:'Meta Ads',objective:'Leads',spend:250,leads:20,impressions:1000,clicks:10,sales:2,revenue:700};
 assert.equal((await call('/api/campaigns',campaign,worker)).status,403);assert.equal((await call('/api/campaigns',campaign,owner)).status,200);
 const data=(await call('/api/data?company=a&month=2026-09',null,worker)).data;assert.equal(data.campaigns.length,0);assert.equal(data.summary.spend,250);assert.equal(data.leads.length,0);
 const task={company_id:'a',date:'2026-09-14',title:'Task',type:'Grabación',status:'Pendiente',notes:'',url:''};assert.equal((await call('/api/tasks',task,worker)).status,200);assert.equal((await call('/api/tasks',{...task,type:'Diseño'},worker)).status,403);
 await call('/api/tasks',{...task,title:'Content',type:'Diseño'},owner);const content=(await call('/api/data?company=a&month=2026-09',null,owner)).data.tasks.find(t=>t.type==='Diseño');assert.ok(content);
 assert.equal((await call('/api/task-approval',{company_id:'a',id:content.id,approval:'Aprobado'},worker)).status,403);assert.equal((await call('/api/task-approval',{company_id:'a',id:content.id,approval:'Aprobado'},owner)).status,200);
 assert.equal((await call('/api/data?company=a&month=2026-09',null,worker)).data.tasks.length,1);
 await call('/api/tasks',{...task,company_id:'b',title:'Other company'},root);
 assert.equal((await call('/api/data?company=b&month=2026-09',null,root)).data.calendarTasks.length,0);
 await DB.prepare('UPDATE companies SET name=? WHERE id=?').bind('GETPES','a').run();
 const aggregate=async cookie=>(await call('/api/data?company=a&month=2026-09',null,cookie)).data.calendarTasks;
 assert.equal((await aggregate(root)).length,3);
 assert.equal((await aggregate(worker)).length,1);
 assert.equal((await aggregate(owner)).length,2);
 assert.ok((await aggregate(worker)).every(t=>t.company_id==='a'&&t.type==='Grabación'));
 await DB.prepare('INSERT INTO user_companies(id,user_id,company_id) VALUES(?,?,?)').bind('assigned-b','worker','b').run();
 assert.equal((await aggregate(worker)).length,2);
 await DB.prepare('DELETE FROM user_companies WHERE id=?').bind('assigned-b').run();
 await DB.prepare('UPDATE companies SET name=? WHERE id=?').bind('a','a').run();
 assert.equal((await call('/api/reports',{company_id:'a'},owner)).status,403);assert.equal((await call('/api/reports',{company_id:'a'},worker)).status,403);
 assert.equal((await call('/api/team?company=a',null,worker)).status,403);assert.equal((await call('/api/team?company=a',null,owner)).data.users.length,2);
 assert.equal((await call('/api/access-requests',{company_id:'a',type:'Nuevo acceso',detail:'Please add Ana'},owner)).status,200);assert.equal((await call('/api/access-requests',{company_id:'b',type:'Nuevo acceso',detail:'forged'},owner)).status,403);assert.equal((await call('/api/access-requests',null,root)).data.requests.length,1);
 assert.equal((await call('/api/users',{id:'worker',role:'staff',username:'worker@getpes.com',companies:['b'],permissions:['campaigns.manage']},root,'PATCH')).status,200);
 assert.equal((await call('/api/companies',null,worker)).status,401);const updated=await login('worker');assert.equal((await call('/api/data?company=a&month=2026-09',null,updated)).status,403);assert.equal((await call('/api/campaigns',{...campaign,company_id:'b'},updated)).status,200);
 assert.equal((await call('/api/users',{role:'staff',username:'bad@getpes.com',companies:['b'],permissions:['users.manage']},root)).status,400);
 // Destructive endpoints require admin, exact confirmation and never delete other companies.
 assert.equal((await call('/api/users',{id:'owner',confirm:'owner@getpes.com'},updated,'DELETE')).status,403);
 assert.equal((await call('/api/users',{id:'root',confirm:'root@getpes.com'},root,'DELETE')).status,400);
 assert.equal((await call('/api/users',{id:'owner',confirm:'wrong'},root,'DELETE')).status,400);
 assert.equal((await call('/api/companies',{id:'a',confirm:'a'},root,'DELETE')).status,409);
 assert.equal((await call('/api/users',{id:'owner',confirm:'owner@getpes.com'},root,'DELETE')).status,200);
 assert.equal((await call('/api/companies',null,owner)).status,401);
 assert.equal((await call('/api/companies',{id:'a',confirm:'a'},updated,'DELETE')).status,403);
 assert.equal((await call('/api/companies',{id:'a',confirm:'wrong'},root,'DELETE')).status,400);
 assert.equal((await call('/api/companies',{id:'a',confirm:'a'},root,'DELETE')).status,200);
 assert.equal(await DB.prepare('SELECT id FROM companies WHERE id=?').bind('a').first(),null);
 assert.ok(await DB.prepare('SELECT id FROM campaigns WHERE company_id=?').bind('b').first());
 assert.ok(await DB.prepare('SELECT id FROM users WHERE id=?').bind('worker').first());
 DB.close();
});
